# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/calc.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/calc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/calc.proto\x12\tmyservice\"\x1d\n\x0b\x43\x61lcRequest\x12\x0e\n\x06inputs\x18\x01 \x03(\t\"0\n\x0c\x43\x61lcResponse\x12 \n\x06outers\x18\x01 \x03(\x0b\x32\x10.myservice.Outer\")\n\x05Outer\x12 \n\x06inners\x18\x01 \x03(\x0b\x32\x10.myservice.Inner\"\x17\n\x05Inner\x12\x0e\n\x06values\x18\x01 \x03(\x02\x32L\n\nCalculator\x12>\n\tCalculate\x12\x16.myservice.CalcRequest\x1a\x17.myservice.CalcResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.calc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CALCREQUEST']._serialized_start=31
  _globals['_CALCREQUEST']._serialized_end=60
  _globals['_CALCRESPONSE']._serialized_start=62
  _globals['_CALCRESPONSE']._serialized_end=110
  _globals['_OUTER']._serialized_start=112
  _globals['_OUTER']._serialized_end=153
  _globals['_INNER']._serialized_start=155
  _globals['_INNER']._serialized_end=178
  _globals['_CALCULATOR']._serialized_start=180
  _globals['_CALCULATOR']._serialized_end=256
# @@protoc_insertion_point(module_scope)
